const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: false },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  type: {type: String, required: false},
  activationKey: { type: String, required: true, unique: false },
  userStatus: { type: String, required: true, unique: false },
  head: { type: String, required: false, unique: false },
  body: { type: String, required: false, unique: false },
  legs: { type: String, required: false, unique: false },
  name: { type: String, required: false, unique: false },
  createdAt: { type: Date, default: Date.now },
  lastLogin: { type: Date },  
  answeredQuestions: { type: [Number], default: [] },
  completedAllQuestionsToday: {type: Boolean,  default: false },
  lastCompletedDate: { type: Date, default: null },
  englishQuestionElo: { type: Number, default: 1000, required: true},
  mathsQuestionElo: { type: Number, default: 1000, required: true},
  scienceQuestionElo: { type: Number, default: 1000, required: true},
  programmingQuestionElo: { type: Number, default: 1000, required: true},
  correct_programmingQuestion: { type: Number, default: 0, required: true},
  correct_mathsQuestion: { type: Number, default: 0, required: true},
  correct_englishQuestion: { type: Number, default: 0, required: true},
  correct_scienceQuestion: { type: Number, default: 0, required: true},
  level: {type: Number, required: true, unique: false, default: 1},
  coins: {type: Number, required: true, unique: false, default: 0},
  extracoins: {type: Number, required: true, unique: false, default: 0},
  happines: {type: Number, required: true, unique: false, default: 3},
  exp: {type: Number, required: true, unique: false, default: 0},
  hp: {type: Number, required: true, unique: false, default: 5, min: 0},
  hpLimit: {type: Number, required: true, unique: false, default: 5, min: 0},
  lastHpLoss: { type: Date, default: null },
  items: { type: [Number], default: [] },
  headSkin: {type: String, required: false, unique: false },
  legSkin: {type: String, required: false, unique: false },
  armSkin: {type: String, required: false, unique: false },
  extracoinsgiven: {type: [Number], default: []},
  editableCharacter: {type: Boolean,  default: false },
  tasks_progress: [
    {
      id_1: {type: Number, required: true, unique: false, default: 0, max: 4},
      id_2: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_3: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_4: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_5: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_6: {type: Number, required: true, unique: false, default: 0, max: 8},
      id_7: {type: Number, required: true, unique: false, default: 0, max: 2},
      id_8: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_9: {type: Number, required: true, unique: false, default: 0, max: 2},
      id_10: {type: Number, required: true, unique: false, default: 0, max: 2},
      id_11: {type: Number, required: true, unique: false, default: 0, max: 40},
      id_12: {type: Number, required: true, unique: false, default: 0, max: 3},
      id_13: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_14: {type: Number, required: true, unique: false, default: 0, max: 3},
      id_15: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_16: {type: Number, required: true, unique: false, default: 0, max: 80},
      id_17: {type: Number, required: true, unique: false, default: 0, max: 40},
      id_18: {type: Number, required: true, unique: false, default: 0, max: 3},
      id_19: {type: Number, required: true, unique: false, default: 0, max: 1000},
      id_20: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_21: {type: Number, required: true, unique: false, default: 0, max: 400},
      id_22: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_23: {type: Number, required: true, unique: false, default: 0, max: 20},
      id_24: {type: Number, required: true, unique: false, default: 0, max: 1},
      id_25: {type: Number, required: true, unique: false, default: 0, max: 4},
    }
  ]
});

const User = mongoose.model('User', userSchema);

module.exports = User;
